use std::fmt;
use std::num::NonZeroU64;

use crate::{FaultState, GpuRuntime};

const WORKGROUP_SIZE: usize = 256;
const PARAMS_SIZE: u64 = 80;
const PARAMS_BYTES: usize = 80;
const LUT_SIZE: usize = 128 * 128;
const GRAIN_SHADER_SOURCE: &str = include_str!("../shaders/grain.wgsl");

/// A checked request for the concrete WGPU film-grain dispatch.
#[derive(Debug, Clone, Copy)]
pub struct GrainPointRequest<'a> {
    /// Packed linear-light RGBA f32 pixels. Alpha is copied unchanged.
    pub pixels: &'a [f32],
    /// Width and height of the packed request (a tile when tiled).
    pub width: u32,
    pub height: u32,
    /// Full image dimensions used to document and validate coordinate origin.
    pub full_width: u32,
    pub full_height: u32,
    /// Full-image coordinate of the request's top-left pixel.
    pub origin_x: u32,
    pub origin_y: u32,
    pub channel: u32,
    pub seed: u64,
    pub zoom: f32,
    pub strength: f32,
    /// The response LUT generated by the immutable `GrainPlan`.
    pub lut: &'a [f32],
}

#[derive(Debug, Clone, PartialEq)]
pub struct GrainPointResult {
    pixels: Vec<f32>,
    dispatches: u32,
}

impl GrainPointResult {
    #[must_use]
    pub fn pixels(&self) -> &[f32] {
        &self.pixels
    }

    #[must_use]
    pub const fn dispatches(&self) -> u32 {
        self.dispatches
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GrainPointError {
    CpuOnly,
    Unhealthy,
    EmptyInput,
    InvalidPixelPacking,
    InvalidDimensions,
    InvalidOrigin,
    InvalidLut,
    TooManyPixels,
    NonFiniteInput { component: usize },
    NonFiniteParameter,
    NonFiniteLut { index: usize },
    TooManyWorkgroups,
    ShaderUnavailable,
    Poll(String),
    Readback(String),
}

impl fmt::Display for GrainPointError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::CpuOnly => formatter.write_str("grain WGPU execution is CPU-only"),
            Self::Unhealthy => formatter.write_str("grain WGPU execution is unhealthy"),
            Self::EmptyInput => formatter.write_str("grain WGPU input is empty"),
            Self::InvalidPixelPacking => {
                formatter.write_str("grain WGPU input is not packed RGBA f32")
            }
            Self::InvalidDimensions => {
                formatter.write_str("grain WGPU dimensions do not match packed pixels")
            }
            Self::InvalidOrigin => {
                formatter.write_str("grain WGPU tile origin is outside the full image")
            }
            Self::InvalidLut => formatter.write_str("grain WGPU response LUT has the wrong size"),
            Self::TooManyPixels => formatter.write_str("grain WGPU input exceeds u32 pixels"),
            Self::NonFiniteInput { component } => write!(
                formatter,
                "grain WGPU input component {component} is non-finite"
            ),
            Self::NonFiniteParameter => formatter.write_str("grain WGPU parameter is non-finite"),
            Self::NonFiniteLut { index } => {
                write!(formatter, "grain WGPU LUT component {index} is non-finite")
            }
            Self::TooManyWorkgroups => {
                formatter.write_str("grain WGPU input exceeds the device workgroup limit")
            }
            Self::ShaderUnavailable => formatter.write_str("grain WGPU shader is unavailable"),
            Self::Poll(error) => write!(formatter, "grain WGPU poll failed: {error}"),
            Self::Readback(error) => write!(formatter, "grain WGPU readback failed: {error}"),
        }
    }
}

impl std::error::Error for GrainPointError {}

impl GpuRuntime {
    /// Dispatches the checked grain shader against one full image or tile.
    ///
    /// The request carries the immutable response LUT and full-image origin,
    /// so this is the same coordinate and response contract as `GrainPlan`.
    #[allow(clippy::too_many_lines)]
    pub fn execute_grain_point(
        &self,
        request: GrainPointRequest<'_>,
    ) -> Result<GrainPointResult, GrainPointError> {
        validate_request(self, request)?;
        let (device, queue) = self.handles().ok_or(GrainPointError::CpuOnly)?;
        if GRAIN_SHADER_SOURCE.is_empty() {
            return Err(GrainPointError::ShaderUnavailable);
        }
        let pixel_bytes = floats_as_bytes(request.pixels);
        let buffer_size =
            u64::try_from(pixel_bytes.len()).map_err(|_| GrainPointError::TooManyPixels)?;
        let input = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("RustTable grain input"),
            size: buffer_size,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let output = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("RustTable grain output"),
            size: buffer_size,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_SRC,
            mapped_at_creation: false,
        });
        let lut_bytes = floats_as_bytes(request.lut);
        let lut_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("RustTable grain response LUT"),
            size: u64::try_from(lut_bytes.len()).map_err(|_| GrainPointError::InvalidLut)?,
            usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let readback = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("RustTable grain readback"),
            size: buffer_size,
            usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        queue.write_buffer(&input, 0, &pixel_bytes);
        queue.write_buffer(&lut_buffer, 0, &lut_bytes);
        let params = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("RustTable grain parameters"),
            size: PARAMS_SIZE,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        queue.write_buffer(&params, 0, &pack_params(request));
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("RustTable grain bindings"),
            entries: &[
                storage_binding(0, true, 16),
                storage_binding(1, false, 16),
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: NonZeroU64::new(PARAMS_SIZE),
                    },
                    count: None,
                },
                storage_binding(3, true, 16),
            ],
        });
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some("RustTable grain pipeline layout"),
            bind_group_layouts: &[Some(&layout)],
            immediate_size: 0,
        });
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("RustTable grain shader"),
            source: wgpu::ShaderSource::Wgsl(GRAIN_SHADER_SOURCE.into()),
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("grain_point"),
            layout: Some(&pipeline_layout),
            module: &shader,
            entry_point: Some("grain_point"),
            compilation_options: wgpu::PipelineCompilationOptions::default(),
            cache: None,
        });
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("RustTable grain bind group"),
            layout: &layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: input.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: output.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: params.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 3,
                    resource: lut_buffer.as_entire_binding(),
                },
            ],
        });
        let workgroups = u32::try_from((request.pixels.len() / 4).div_ceil(WORKGROUP_SIZE))
            .map_err(|_| GrainPointError::TooManyWorkgroups)?;
        let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
            label: Some("RustTable grain encoder"),
        });
        {
            let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("grain_point"),
                timestamp_writes: None,
            });
            pass.set_pipeline(&pipeline);
            pass.set_bind_group(0, &bind_group, &[]);
            pass.dispatch_workgroups(workgroups, 1, 1);
        }
        encoder.copy_buffer_to_buffer(&output, 0, &readback, 0, buffer_size);
        let _submission = queue.submit([encoder.finish()]);
        let slice = readback.slice(..);
        let (sender, receiver) = std::sync::mpsc::channel();
        slice.map_async(wgpu::MapMode::Read, move |result| {
            let _ = sender.send(result.map_err(|error| error.to_string()));
        });
        device
            .poll(wgpu::PollType::Wait {
                submission_index: None,
                timeout: None,
            })
            .map_err(|error| GrainPointError::Poll(error.to_string()))?;
        receiver
            .recv()
            .map_err(|error| GrainPointError::Readback(error.to_string()))?
            .map_err(GrainPointError::Readback)?;
        let view = slice
            .get_mapped_range()
            .map_err(|error| GrainPointError::Readback(error.to_string()))?;
        let (chunks, remainder) = view.as_chunks::<4>();
        debug_assert!(remainder.is_empty());
        let pixels = chunks
            .iter()
            .map(|bytes| f32::from_le_bytes(*bytes))
            .collect();
        drop(view);
        readback.unmap();
        Ok(GrainPointResult {
            pixels,
            dispatches: 1,
        })
    }
}

fn storage_binding(binding: u32, read_only: bool, minimum: u64) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Storage { read_only },
            has_dynamic_offset: false,
            min_binding_size: NonZeroU64::new(minimum),
        },
        count: None,
    }
}

fn validate_request(
    runtime: &GpuRuntime,
    request: GrainPointRequest<'_>,
) -> Result<(), GrainPointError> {
    if runtime.is_cpu_only() {
        return Err(GrainPointError::CpuOnly);
    }
    if !matches!(
        runtime.snapshot().state,
        FaultState::Healthy | FaultState::Degraded
    ) {
        return Err(GrainPointError::Unhealthy);
    }
    if request.pixels.is_empty() {
        return Err(GrainPointError::EmptyInput);
    }
    if !request.pixels.len().is_multiple_of(4) {
        return Err(GrainPointError::InvalidPixelPacking);
    }
    let pixel_count = request.pixels.len() / 4;
    if pixel_count > u32::MAX as usize {
        return Err(GrainPointError::TooManyPixels);
    }
    let expected = u64::from(request.width) * u64::from(request.height);
    if request.width == 0 || request.height == 0 || expected != pixel_count as u64 {
        return Err(GrainPointError::InvalidDimensions);
    }
    if request.full_width == 0
        || request.full_height == 0
        || u64::from(request.origin_x) + u64::from(request.width) > u64::from(request.full_width)
        || u64::from(request.origin_y) + u64::from(request.height) > u64::from(request.full_height)
    {
        return Err(GrainPointError::InvalidOrigin);
    }
    if request.lut.len() != LUT_SIZE {
        return Err(GrainPointError::InvalidLut);
    }
    if let Some(component) = request.pixels.iter().position(|value| !value.is_finite()) {
        return Err(GrainPointError::NonFiniteInput { component });
    }
    if request.channel > 3
        || !request.zoom.is_finite()
        || request.zoom <= 0.0
        || !request.strength.is_finite()
    {
        return Err(GrainPointError::NonFiniteParameter);
    }
    if let Some(index) = request.lut.iter().position(|value| !value.is_finite()) {
        return Err(GrainPointError::NonFiniteLut { index });
    }
    let workgroups = pixel_count.div_ceil(WORKGROUP_SIZE) as u64;
    if workgroups > u64::from(runtime.snapshot().limits.max_workgroups_per_dimension) {
        return Err(GrainPointError::TooManyWorkgroups);
    }
    Ok(())
}

fn pack_params(request: GrainPointRequest<'_>) -> [u8; PARAMS_BYTES] {
    let mut bytes = [0_u8; PARAMS_BYTES];
    let values = [
        u32::try_from(request.pixels.len() / 4).unwrap_or(u32::MAX),
        request.width,
        request.height,
        request.channel,
        request.full_width,
        request.full_height,
        request.origin_x,
        request.origin_y,
        u32::try_from(request.seed & u64::from(u32::MAX)).expect("masked seed fits"),
        u32::try_from(request.seed >> 32).expect("shifted seed fits"),
    ];
    for (index, value) in values.into_iter().enumerate() {
        bytes[index * 4..index * 4 + 4].copy_from_slice(&value.to_le_bytes());
    }
    bytes[40..44].copy_from_slice(&request.zoom.to_le_bytes());
    bytes[44..48].copy_from_slice(&request.strength.to_le_bytes());
    bytes
}

fn floats_as_bytes(values: &[f32]) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(values.len() * 4);
    for value in values {
        bytes.extend_from_slice(&value.to_le_bytes());
    }
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_grain_shader_parses_as_wgsl() {
        let module =
            naga::front::wgsl::parse_str(GRAIN_SHADER_SOURCE).expect("grain shader syntax");
        naga::valid::Validator::new(
            naga::valid::ValidationFlags::all(),
            naga::valid::Capabilities::all(),
        )
        .validate(&module)
        .expect("grain shader validation");
    }

    #[test]
    fn parameters_are_stable_and_include_tile_origin() {
        let request = GrainPointRequest {
            pixels: &[0.0; 4],
            width: 1,
            height: 1,
            full_width: 8,
            full_height: 6,
            origin_x: 3,
            origin_y: 4,
            channel: 2,
            seed: 0x1122_3344_5566_7788,
            zoom: 1.25,
            strength: 25.0,
            lut: &vec![0.0; LUT_SIZE],
        };
        let bytes = pack_params(request);
        assert_eq!(
            u32::from_le_bytes(bytes[24..28].try_into().expect("origin")),
            3
        );
        assert_eq!(
            u32::from_le_bytes(bytes[28..32].try_into().expect("origin")),
            4
        );
        assert_eq!(
            f32::from_le_bytes(bytes[40..44].try_into().expect("zoom")).to_bits(),
            1.25_f32.to_bits()
        );
        assert_eq!(bytes.len(), PARAMS_BYTES);
    }

    #[tokio::test]
    async fn grain_dispatch_preserves_identity_at_zero_strength_when_gpu_is_available() {
        let Ok(runtime) = GpuRuntime::initialize(crate::GpuRuntimeConfig::default()).await else {
            return;
        };
        if runtime.is_cpu_only() {
            return;
        }
        let input = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8];
        let result = runtime
            .execute_grain_point(GrainPointRequest {
                pixels: &input,
                width: 2,
                height: 1,
                full_width: 2,
                full_height: 1,
                origin_x: 0,
                origin_y: 0,
                channel: 2,
                seed: 7,
                zoom: 1.0,
                strength: 0.0,
                lut: &vec![0.0; LUT_SIZE],
            })
            .expect("grain dispatch");
        assert_eq!(result.dispatches(), 1);
        assert_eq!(result.pixels(), &input);
    }
}
