//! Source-to-Rust responsibility map for the bounded Color Contrast CPU leaf.

#![forbid(unsafe_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ColorContrastSourceMapEntry {
    pub responsibility: &'static str,
    pub native_symbol: &'static str,
    pub native_file: &'static str,
    pub native_lines: &'static str,
    pub rust_symbol: &'static str,
    pub status: ColorContrastPortStatus,
    pub notes: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorContrastPortStatus {
    Ported,
    RustAdaptation,
    ExistingDependency,
    ExplicitlyDeferred,
}

pub const COLOR_CONTRAST_SOURCE_MAP: &[ColorContrastSourceMapEntry] = &[
    ColorContrastSourceMapEntry {
        responsibility: "native-metadata-and-parameter-abi",
        native_symbol: "name / aliases / flags / default_group / default_colorspace / dt_iop_colorcontrast_params_t",
        native_file: "src/iop/colorcontrast.c; src/develop/imageop.h; src/common/colorspaces.h",
        native_lines: "colorcontrast.c:34-80,91-107; imageop.h:51-110; colorspaces.h:40-51",
        rust_symbol: "metadata constants / ColorContrastParametersV1 / ColorContrastParametersV2",
        status: ColorContrastPortStatus::Ported,
        notes: "Source-derived names, flags, groups, colorspace, declaration order, sizes, defaults, and payload bits only; operation-local execution policy is mapped separately.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "operation-local-descriptor-policy",
        native_symbol: "native metadata plus no direct equivalent for Rust descriptor admission policy",
        native_file: "src/iop/colorcontrast.c; src/develop/tiling.c",
        native_lines: "colorcontrast.c:34-107,165-221; tiling.c:2101-2125",
        rust_symbol: "colorcontrast_descriptor / lab_io",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "Native has no operation-local contract that rejects non-finite samples, guarantees four initialized lanes, chooses a 256-pixel preferred edge, or accounts a transactional staging raster; those descriptor claims are Rust policy.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "visible-steepness-slider-precision",
        native_symbol: "DT_MODULE_INTROSPECTION / parameter annotations / dt_bauhaus_slider_from_params",
        native_file: "src/iop/colorcontrast.c; tools/introspection/parser.pm; src/common/introspection.h; src/develop/imageop_gui.c",
        native_lines: "colorcontrast.c:33-42,304-319; parser.pm:66-83; introspection.h:74-80; imageop_gui.c:89-107",
        rust_symbol: "colorcontrast_descriptor visible steepness parameter precision",
        status: ColorContrastPortStatus::Ported,
        notes: "Introspection parses each steepness field's MIN 0.0 and MAX 5.0 annotations into Float.Min and Float.Max. dt_bauhaus_slider_from_params derives top=5 and digits=MAX(2, -floor(log10(top/100)+0.1))=2, then passes two digits to both visible sliders. The hidden offsets are not constructed as GUI sliders.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "native-description",
        native_symbol: "description / dt_iop_set_description",
        native_file: "src/iop/colorcontrast.c",
        native_lines: "81-89",
        rust_symbol: "not represented by the operation-local descriptor",
        status: ColorContrastPortStatus::ExplicitlyDeferred,
        notes: "The five source description strings are not represented by this leaf.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "legacy-history-migration",
        native_symbol: "legacy_params",
        native_file: "src/iop/colorcontrast.c",
        native_lines: "109-150",
        rust_symbol: "ColorContrastHistory / migrate_v1_to_v2",
        status: ColorContrastPortStatus::Ported,
        notes: "The direct v1-to-v2 field copy and forced bounded-mode int are source-derived; opaque future retention is additive codec policy.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "required-input-format-imagebuf-boundary",
        native_symbol: "dt_iop_have_required_input_format / dt_iop_copy_image_roi",
        native_file: "src/iop/colorcontrast.c; src/develop/imageop.c; src/develop/imageop.h; src/common/imagebuf.c; src/common/imagebuf.h",
        native_lines: "colorcontrast.c:177-183; imageop.c:3950-3988; imageop.h:578-587; imagebuf.c:183-238; imagebuf.h:103-107",
        rust_symbol: "typed leaf requires prevalidated four-lane input and an identical input/output ROI",
        status: ColorContrastPortStatus::ExplicitlyDeferred,
        notes: "Native actual-channel copy-through, distinct-ROI cropping, zero padding, and trouble publication are outside the equal-ROI typed leaf.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "bounded-scaling-helper",
        native_symbol: "clamped_scaling / CLAMPS",
        native_file: "src/iop/colorcontrast.c; src/common/darktable.h",
        native_lines: "colorcontrast.c:151-164; darktable.h:285",
        rust_symbol: "source-ordered selected-lane arithmetic / darktable_clamps",
        status: ColorContrastPortStatus::Ported,
        notes: "This status covers the source-selected lane arithmetic and exact CLAMPS branch order; deterministic fused Rust rounding, finite failure, and lane-count policy are mapped separately.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "explicit-fused-rounding-rust-adaptation",
        native_symbol: "process / clamped_scaling / add_iop / CMAKE_C_FLAGS_RELEASE / __FAST_MATH__",
        native_file: "src/iop/colorcontrast.c; src/iop/CMakeLists.txt; src/CMakeLists.txt; src/common/math.h",
        native_lines: "colorcontrast.c:151-220; iop/CMakeLists.txt:16-59,125; src/CMakeLists.txt:710-733; math.h:378-402",
        rust_symbol: "ColorContrastPlan::evaluate_pixel explicit f32 mul_add",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "Native source spells multiplication plus addition, and src/iop/CMakeLists.txt:125 registers Color Contrast as an ordinary iop. Although the retained Release defaults include O3 and compiler fast-math flags, contraction is compiler/target/profile dependent and no exact authoritative native tuple is established. Fused rounding is therefore a deterministic Rust adaptation: explicit mul_add maps input=0xc2e60bbb, slope=0x3f9aead4, and offset=0x40c88889 to 0xc304f1cf rather than separate-rounding 0xc304f1d0. Noncontracting native profiles are explicitly deferred. architecture/rusttable-numerics.toml registers crates/rusttable-processing/src/operations/colorcontrast/leaf.rs as ExplicitFused.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "native-for-each-channel-lane-policy",
        native_symbol: "DT_PIXEL_SIMD_CHANNELS / for_each_channel / copy_pixel_nontemporal",
        native_file: "src/common/dttypes.h; src/develop/imageop.h; src/iop/colorcontrast.c",
        native_lines: "dttypes.h:59-114; imageop.h:603-624; colorcontrast.c:151-164,193-218",
        rust_symbol: "ColorContrastLanePolicy::DeterministicFourLaneRustAdaptation",
        status: ColorContrastPortStatus::ExplicitlyDeferred,
        notes: "Native processes three lanes without vectorization and four otherwise, and does not unconditionally guarantee spare/alpha; Rust always initializes and preserves lane four.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "native-memory-alignment-and-store-policy",
        native_symbol: "DT_IS_ALIGNED / DT_CACHELINE_BYTES / dt_aligned_pixel_t / copy_pixel_nontemporal",
        native_file: "src/iop/colorcontrast.c; src/common/darktable.h; src/common/dttypes.h; src/develop/imageop.h",
        native_lines: "colorcontrast.c:151-162,184-203; darktable.h:188-192; dttypes.h:41-60; imageop.h:603-624,626-656",
        rust_symbol: "ColorContrastPixel / Vec<ColorContrastPixel> / scalar evaluation / copy_from_slice",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "Native process applies DT_IS_ALIGNED to input and output using DT_CACHELINE_BYTES (128 on Apple AArch64, 64 otherwise), declares four-float dt_aligned_pixel_t locals with 16-byte alignment, and uses architecture-dependent copy_pixel_nontemporal stores with visibility-fence obligations. This leaf instead uses ordinary Vec scalar Rust storage with ColorContrastPixel's natural f32 alignment and ordinary publication; that is a Rust adaptation with no native cache-line, aligned-local, nontemporal-store, or fence guarantee. Native tile alignment and Rust allocation-budget facts remain separate.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "native-openmp-scheduling-and-declare-simd",
        native_symbol: "DT_OMP_DECLARE_SIMD(aligned(in,out:64) aligned(slope,offset,low,high)) / unbounded DT_OMP_FOR() / bounded DT_OMP_FOR() / DT_OMP_PRAGMA",
        native_file: "src/iop/colorcontrast.c; src/common/darktable.h",
        native_lines: "colorcontrast.c:152-163,194-219; darktable.h:117-132",
        rust_symbol: "ColorContrastPlan::execute_with_cancel serial row-major pixel loop / ColorContrastPlan::evaluate_pixel scalar channel loop",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "Native attaches DT_OMP_DECLARE_SIMD(aligned(in,out:64) aligned(slope,offset,low,high)) to clamped_scaling and applies DT_OMP_FOR() separately to both the unbounded and bounded process loops. src/common/darktable.h maps both macros through DT_OMP_PRAGMA: with _OPENMP, the helper receives an omp declare simd alignment contract and each process loop becomes parallel for default(firstprivate) schedule(static); without _OPENMP, those pragmas are empty. Rust instead traverses pixels once in serial row-major order and evaluates channels in a scalar loop. That scheduling/SIMD choice is a Rust adaptation; native OpenMP static scheduling, declare-SIMD function generation, and the 64-byte in/out alignment clause remain explicitly deferred.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "cpu-process-equations",
        native_symbol: "process",
        native_file: "src/iop/colorcontrast.c",
        native_lines: "166-221",
        rust_symbol: "ColorContrastPlan::execute_with_cancel with deterministic four-lane Rust adaptation",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "L/a/b arithmetic preserves the source expression and bounded branch order, but explicit fused rounding, deterministic alpha processing, and fail-closed finite checks are Rust adaptations. Native noncontracting compiler/target/profile combinations remain deferred.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "commit-and-piece-lifetime",
        native_symbol: "commit_params / init_pipe / cleanup_pipe",
        native_file: "src/iop/colorcontrast.c",
        native_lines: "267-295",
        rust_symbol: "ColorContrastConfig / PreservedFiniteF32 / ColorContrastPlan",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "Native mallocs piece data and copies every float bit pattern, including NaN and infinity, without validation; Rust ownership replaces malloc/free and rejects non-finite committed parameters while preserving every finite bit pattern.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "finite-cancellation-publication",
        native_symbol: "process has no finite validation, cancellation callback, or transactional staging",
        native_file: "src/iop/colorcontrast.c",
        native_lines: "166-221",
        rust_symbol: "ColorContrastExecutionError / ColorContrastPlan::execute_into_with_cancel",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "Native writes directly to its output and lets non-finite input or arithmetic flow through its equations; Rust rejects non-finite input/output, polls cancellation, and publishes only after a complete staged raster succeeds.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "native-default-tiling-and-rust-allocation-budget",
        native_symbol: "flags / default_tiling_callback",
        native_file: "src/iop/colorcontrast.c; src/develop/tiling.c; src/develop/tiling.h",
        native_lines: "colorcontrast.c:91-94; tiling.c:2101-2125; tiling.h:24-60",
        rust_symbol: "COLOR_CONTRAST_NATIVE_TILING_* / colorcontrast_descriptor / ColorContrastAllocationBudget",
        status: ColorContrastPortStatus::RustAdaptation,
        notes: "For equal ROIs native reports host/OpenCL factor 2.0 (one input plus one output), maxbuf 1.0, zero overhead and overlap, and alignment 1. Rust preserves the input/output, overlap, and alignment facts but adds a preferred edge of 256 and one full staging raster; execute_into's payload budget is width*height*16 staging bytes, excluding allocator metadata/rounding, and it accounts three resident raster payloads.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "raster-dimensions-and-descriptor-types",
        native_symbol: "roi_out width/height and operation contract",
        native_file: "src/iop/colorcontrast.c",
        native_lines: "166-192",
        rust_symbol: "rusttable_processing::RasterDimensions / descriptor types",
        status: ColorContrastPortStatus::ExistingDependency,
        notes: "The leaf consumes these existing shared Rust value types without modifying their owners.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "opencl-kernel",
        native_symbol: "process_cl / init_global / cleanup_global / colorcontrast",
        native_file: "src/iop/colorcontrast.c; data/kernels/extended.cl; data/kernels/common.h",
        native_lines: "colorcontrast.c:223-264; extended.cl:239-255; common.h:23-30",
        rust_symbol: "ColorContrastCapabilities::require_gpu",
        status: ColorContrastPortStatus::ExplicitlyDeferred,
        notes: "Program 8 host setup and the colorcontrast kernel are inventoried but unavailable in this CPU leaf.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "gtk-controls",
        native_symbol: "gui_update / gui_init",
        native_file: "src/iop/colorcontrast.c",
        native_lines: "297-321",
        rust_symbol: "ColorContrastCapabilities::require_gtk",
        status: ColorContrastPortStatus::ExplicitlyDeferred,
        notes: "Native slider construction, update, and tooltips remain outside the operation-local CPU leaf; the source-derived two-digit visible-slider precision is represented separately in the local descriptor.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "masks-and-outer-blending",
        native_symbol: "IOP_FLAGS_SUPPORTS_BLENDING and shared blend pipeline",
        native_file: "src/iop/colorcontrast.c; src/develop/blend.c",
        native_lines: "colorcontrast.c:92-95",
        rust_symbol: "ColorContrastCapabilities::require_masks_and_outer_blending",
        status: ColorContrastPortStatus::ExplicitlyDeferred,
        notes: "The native capability flag is recorded, but shared mask, blend-if, mode, and opacity composition are unavailable.",
    },
    ColorContrastSourceMapEntry {
        responsibility: "production-routing",
        native_symbol: "history materialization / operation order / registry / pixelpipe dispatch / app editing",
        native_file: "shared Rust integration hubs",
        native_lines: "outside bounded native CPU leaf",
        rust_symbol: "ColorContrastCapabilities::require_production_routing",
        status: ColorContrastPortStatus::ExplicitlyDeferred,
        notes: "No shared integration hub is modified or claimed by this standalone leaf.",
    },
];
