use crate::model::Discovered;

pub(crate) fn map_discovered(kind: &str, name: &str, path: &str) -> Option<Discovered> {
    let (category, status, issue_sequences, redesign_note) = match kind {
        "iop" if IOPS.contains(&name) => (
            "darkroom",
            "required",
            iop_issue(name),
            None,
        ),
        "lib" if LIBS.contains(&name) => (lib_category(name), "required", vec!["0057"], None),
        "view" if VIEWS.contains(&name) => (view_category(name), "required", view_issue(name), None),
        "format" if FORMATS.contains(&name) => {
            ("RAW/raster I/O", "required", format_issue(name), None)
        }
        "storage" if STORAGES.contains(&name) => (
            "export/storage",
            "required",
            storage_issue(name),
            None,
        ),
        "lua" if LUA_APIS.contains(&name) => (
            "scripting",
            "redesigned",
            vec!["0035"],
            Some("RustTable exposes the Lua-compatible boundary through a versioned host.".to_owned()),
        ),
        "build-option" if BUILD_OPTIONS.contains(&name) => (
            "packaging",
            "redesigned",
            vec!["0014"],
            Some("RustTable records the option as a Rust-owned platform or feature policy.".to_owned()),
        ),
        "opencl" if OPENCL_PROGRAMS.contains(&name) => (
            "darkroom",
            "redesigned",
            vec!["0136"],
            Some("OpenCL kernels are reference evidence; RustTable uses the reviewed WGPU registry and CPU fallback.".to_owned()),
        ),
        _ => return None,
    };
    Some(Discovered {
        id: format!("{kind}.{name}"),
        reference_path: path.to_owned(),
        reference_symbol: name.to_owned(),
        category,
        status,
        issue_sequences: issue_sequences.into_iter().map(str::to_owned).collect(),
        test_evidence: vec![format!("reference-scan:{kind}")],
        redesign_note,
    })
}

fn lib_category(name: &str) -> &'static str {
    if ["camera", "live_view"].contains(&name) {
        "camera/tethering"
    } else if ["location", "map_settings", "map_locations", "geotagging"].contains(&name) {
        "map/geotagging"
    } else if name == "print_settings" {
        "printing"
    } else if ["export", "export_metadata"].contains(&name) {
        "export/storage"
    } else {
        "catalog/library"
    }
}

fn view_category(name: &str) -> &'static str {
    match name {
        "map" => "map/geotagging",
        "print" => "printing",
        "tethering" => "camera/tethering",
        "darkroom" => "darkroom",
        _ => "catalog/library",
    }
}

fn view_issue(name: &str) -> Vec<&'static str> {
    match name {
        "map" => vec!["0060"],
        "print" | "tethering" => vec!["0035"],
        _ => vec!["0057"],
    }
}

fn format_issue(name: &str) -> Vec<&'static str> {
    match name {
        "copy" => vec!["0239"],
        "jpeg" => vec!["0069", "0240"],
        "png" => vec!["0070", "0241"],
        "tiff" => vec!["0071", "0242"],
        "exr" => vec!["0072", "0248"],
        "jxl_format" => vec!["0073", "0244"],
        "webp" => vec!["0074", "0245"],
        "avif_format" => vec!["0075", "0246"],
        "heif_format" => vec!["0075", "0247"],
        "j2k" => vec!["0076", "0249"],
        "xcf" | "gimp_xcf" => vec!["0083", "0251"],
        "pdf" => vec!["0250"],
        "ppm" | "pfm" => vec!["0076", "0243"],
        _ => vec!["0235"],
    }
}

fn storage_issue(name: &str) -> Vec<&'static str> {
    match name {
        "disk" => vec!["0254"],
        "email" => vec!["0255"],
        "gallery" | "piwigo" => vec!["0256"],
        "latex" => vec!["0257"],
        _ => vec!["0235"],
    }
}

pub(crate) fn iop_issue(name: &str) -> Vec<&'static str> {
    let issue = match name {
        "rawprepare" => "0146",
        "demosaic" => "0147",
        "temperature" => "0148",
        "cacorrect" | "cacorrectrgb" => "0149",
        "hotpixels" => "0150",
        "denoiseprofile" => "0151",
        "rawdenoise" => "0152",
        "nlmeans" => "0153",
        "hazeremoval" => "0154",
        "atrous" => "0155",
        "equalizer" => "0156",
        "sharpen" => "0157",
        "highpass" => "0158",
        "lowpass" => "0159",
        "bilat" => "0160",
        "bilateral" => "0161",
        "blurs" => "0162",
        "diffuse" => "0163",
        "exposure" => "0164",
        "basicadj" => "0165",
        "lowlight" => "0166",
        "profile_gamma" => "0167",
        "gamma" => "0168",
        "rgblevels" => "0169",
        "levels" => "0170",
        "toneequal" => "0171",
        "filmicrgb" => "0172",
        "filmic" => "0173",
        "basecurve" => "0174",
        "rgbcurve" => "0175",
        "tonecurve" => "0176",
        "zonesystem" => "0177",
        "tonemap" => "0178",
        "globaltonemap" => "0179",
        "sigmoid" => "0180",
        "agx" => "0181",
        "negadoctor" => "0182",
        "splittoning" => "0183",
        "monochrome" => "0184",
        "vibrance" => "0185",
        "velvia" => "0186",
        "colorequal" => "0187",
        "colorcontrast" => "0188",
        "colorbalancergb" => "0189",
        "colorbalance" => "0190",
        "colisa" => "0191",
        "colorout" => "0192",
        "colorin" => "0193",
        "primaries" => "0194",
        "colorcorrection" => "0195",
        "channelmixerrgb" => "0196",
        "channelmixer" => "0197",
        "lut3d" => "0198",
        "colormapping" => "0199",
        "colortransfer" => "0200",
        "colorize" => "0201",
        "colorchecker" => "0202",
        "colorharmonizer" => "0203",
        "colorzones" => "0204",
        "highlights" => "0205",
        "colorreconstruct" => "0206",
        "rawoverexposed" => "0207",
        "overexposed" => "0208",
        "rasterfile" => "0209",
        "vignette" => "0210",
        "graduatednd" => "0211",
        "grain" => "0212",
        "bloom" => "0213",
        "soften" => "0214",
        "shadhi" => "0215",
        "relight" => "0216",
        "dither" => "0218",
        "borders" => "0219",
        "watermark" => "0220",
        "crop" => "0223",
        "flip" => "0224",
        "rotatepixels" => "0225",
        "scalepixels" => "0226",
        "finalscale" => "0227",
        "enlargecanvas" => "0228",
        "ashift" => "0229",
        "lens" => "0230",
        "liquify" => "0231",
        "spots" => "0232",
        "retouch" => "0233",
        "mask_manager" => "0234",
        _ => "0235",
    };
    vec![issue]
}

const IOPS: &[&str] = &[
    "colorharmonizer",
    "rawprepare",
    "soften",
    "bloom",
    "highpass",
    "lowpass",
    "shadhi",
    "colorreconstruct",
    "tonemap",
    "tonecurve",
    "colisa",
    "gamma",
    "temperature",
    "colorcorrection",
    "basicadj",
    "exposure",
    "equalizer",
    "rgbcurve",
    "colorbalance",
    "colorin",
    "colorout",
    "colorchecker",
    "clipping",
    "enlargecanvas",
    "crop",
    "sharpen",
    "dither",
    "monochrome",
    "basecurve",
    "colorzones",
    "highlights",
    "overlay",
    "rawoverexposed",
    "velvia",
    "vignette",
    "splittoning",
    "grain",
    "clahe",
    "bilateral",
    "profile_gamma",
    "colortransfer",
    "colormapping",
    "channelmixer",
    "graduatednd",
    "relight",
    "zonesystem",
    "demosaic",
    "rotatepixels",
    "scalepixels",
    "atrous",
    "cacorrect",
    "overexposed",
    "hotpixels",
    "lowlight",
    "spots",
    "retouch",
    "liquify",
    "rawdenoise",
    "borders",
    "nlmeans",
    "colorcontrast",
    "levels",
    "rgblevels",
    "colorize",
    "invert",
    "vibrance",
    "flip",
    "finalscale",
    "globaltonemap",
    "bilat",
    "denoiseprofile",
    "defringe",
    "ashift",
    "hazeremoval",
    "filmic",
    "mask_manager",
    "lut3d",
    "toneequal",
    "filmicrgb",
    "negadoctor",
    "channelmixerrgb",
    "censorize",
    "colorbalancergb",
    "cacorrectrgb",
    "diffuse",
    "blurs",
    "sigmoid",
    "agx",
    "primaries",
    "colorequal",
    "rasterfile",
    "watermark",
    "lens",
];

const LIBS: &[&str] = &[
    "import",
    "export",
    "copy_history",
    "styles",
    "tagging",
    "image",
    "select",
    "collect",
    "recentcollect",
    "filtering",
    "metadata",
    "metadata_view",
    "navigation",
    "histogram",
    "history",
    "snapshots",
    "modulegroups",
    "backgroundjobs",
    "colorpicker",
    "masks",
    "session",
    "duplicate",
    "ioporder",
    "viewswitcher",
    "darktable_label",
    "colorlabels",
    "ratings",
    "filter",
    "lighttable_mode",
    "view_toolbox",
    "module_toolbox",
    "filmstrip",
    "hinter",
    "global_toolbox",
    "timeline",
    "image_infos",
    "log_history",
    "midi",
    "gamepad",
    "camera",
    "live_view",
    "location",
    "map_settings",
    "map_locations",
    "geotagging",
    "print_settings",
    "neural_restore",
];

const VIEWS: &[&str] = &[
    "darkroom",
    "lighttable",
    "slideshow",
    "map",
    "tethering",
    "print",
];
const FORMATS: &[&str] = &[
    "copy",
    "jpeg",
    "pdf",
    "png",
    "ppm",
    "pfm",
    "tiff",
    "jxl_format",
    "heif_format",
    "webp",
    "exr",
    "j2k",
    "avif_format",
    "gimp_xcf",
];
const STORAGES: &[&str] = &["disk", "email", "gallery", "latex", "piwigo"];
const LUA_APIS: &[&str] = &[
    "early_types",
    "early_events",
    "early_modules",
    "early_format",
    "early_storage",
    "early_lib",
    "early_view",
    "glist",
    "image",
    "styles",
    "print",
    "configuration",
    "preferences",
    "database",
    "gui",
    "luastorages",
    "tags",
    "film",
    "call",
    "view",
    "events",
    "init",
    "widget",
    "lualib",
    "gettext",
    "guides",
    "cairo",
    "password",
    "util",
    "metadata",
    "ai",
];
const BUILD_OPTIONS: &[&str] = &[
    "USE_CAMERA_SUPPORT",
    "USE_COLORD",
    "USE_MAP",
    "USE_LUA",
    "DONT_USE_INTERNAL_LUA",
    "USE_KWALLET",
    "USE_LIBSECRET",
    "USE_UNITY",
    "USE_OPENMP",
    "USE_OPENCL",
    "USE_GRAPHICSMAGICK",
    "USE_IMAGEMAGICK",
    "USE_DARKTABLE_PROFILING",
    "CUSTOM_CFLAGS",
    "BINARY_PACKAGE_BUILD",
    "USE_XMLLINT",
    "USE_PORTMIDI",
    "USE_OPENJPEG",
    "USE_JXL",
    "USE_WEBP",
    "USE_AVIF",
    "USE_HEIF",
    "USE_XCF",
    "USE_ISOBMFF",
    "USE_LIBRAW",
    "USE_AI",
    "DONT_USE_INTERNAL_LIBRAW",
    "BUILD_CMSTEST",
    "USE_OPENEXR",
    "BUILD_PRINT",
    "BUILD_RS_IDENTIFY",
    "VALIDATE_APPDATA_FILE",
    "BUILD_MSYS2_INSTALL",
    "BUILD_NOISE_TOOLS",
    "BUILD_CURVE_TOOLS",
    "USE_GMIC",
    "USE_ICU",
    "FORCE_COLORED_OUTPUT",
    "USE_SDL2",
    "TESTBUILD_OPENCL_PROGRAMS",
    "USE_MAC_INTEGRATION",
];
const OPENCL_PROGRAMS: &[&str] = &[
    "demosaic_ppg",
    "atrous",
    "basic",
    "blendop",
    "highpass",
    "nlmeans",
    "gaussian",
    "sharpen",
    "extended",
    "soften",
    "bilateral",
    "denoiseprofile",
    "bloom",
    "colorreconstruction",
    "demosaic_other",
    "demosaic_vng",
    "demosaic_markesteijn",
    "liquify",
    "basecurve",
    "locallaplacian",
    "dwt",
    "retouch",
    "filmic",
    "colorspaces",
    "basicadj",
    "rgbcurve",
    "guided_filter",
    "hazeremoval",
    "lut3d",
    "rgblevels",
    "negadoctor",
    "demosaic_rcd",
    "channelmixer",
    "diffuse",
    "blurs",
    "bspline",
    "sigmoid",
    "colorequal",
    "capture",
    "agx",
    "colorharmonizer",
    "overlay",
];
